baseURL = 'http://aurabit.github.io/TLmain/'
languageCode = 'en-us'
title = 'Twin Ludens'
theme = 'LoveIt'
[author]
  name = "TL"

  [params.home]
      # LoveIt NEW | 0.2.0 amount of RSS pages
      rss = 10
      # Home page profile
      [params.home.profile]
        enable = true
        # Gravatar Email for preferred avatar in home page
        gravatarEmail = ""
        # URL of avatar shown in home page
        avatarURL = ""
        # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
        title = ""
        # subtitle shown in home page (HTML format is supported)
        subtitle = "You have power over your mind - not outside events. Realize this, and you will find strength."
        # whether to use typeit animation for subtitle
        typeit = true
        # whether to show social links
        social = true
        # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
        disclaimer = ""
      # Home page posts
      [params.home.posts]
        enable = true
        # special amount of posts in each home posts page
        paginate = 6
        # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
        # default behavior when you don't set "hiddenFromHomePage" in front matter
        defaultHiddenFromHomePage = false

        # Footer config
          [params.footer]
            enable = true
            # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
            custom = ''
            # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
            hugo = false
            # LoveIt NEW | 0.2.0 whether to show copyright info
            copyright = true
            # LoveIt NEW | 0.2.0 whether to show the author
            author = true
            # Site creation time
            since = 2019
            # ICP info only in China (HTML format is supported)
            icp = ""
            # license info (HTML format is supported)
            license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

          # LoveIt NEW | 0.2.0 Section (all posts) page config
          [params.section]
            # special amount of posts in each section page
            paginate = 20
            # date format (month and day)
            dateFormat = "01-02"
            # amount of RSS pages
            rss = 10


  [params.social]
    Linkedin = ""
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = "TwinLudens"
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Discord = ""
    DiscordInvite = ""
    Lichess = ""
    ORCID = ""
    Pleroma = ""
    Email = "twinludens@gmail.com"

    [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Twin Ludens"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false
